services:
  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hacker-news-scraper
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5420:5432"

volumes:
  postgres_data:
